package br.com.testeComSpring.model;

import javax.validation.ConstraintViolationException;

import org.junit.Before;
import org.junit.Rule;
import org.junit.rules.ExpectedException;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.jdbc.EmbeddedDatabaseConnection;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.junit4.SpringRunner;

import br.com.testeComSpring.repository.ClienteRepository;

@RunWith(SpringRunner.class)
@DataJpaTest
@AutoConfigureTestDatabase(connection = EmbeddedDatabaseConnection.H2)
public class ClienteValidationTest {
	
	private Cliente cliente;
	
	@Autowired
	ClienteRepository clienteRepository;
	
	@Rule
	public ExpectedException expectedException = ExpectedException.none();
	
	@Before
	public void setUp() {
		cliente = new Cliente("Jamil", "Rua 1", "32344334");
	}
	
	
	public void deveLancarExcecaoAoSalvarClienteComNomeNulo() {
		
		expectedException.expect(ConstraintViolationException.class);
		expectedException.expectMessage("Nome n√£o pode ser vazio");
		
		cliente.setNome(null);
		clienteRepository.save(cliente);
	}

}
